PROGRAM helloWorld
IMPLICIT NONE 
INTEGER  NTHREADS, TID, OMP_GET_NUM_THREADS, OMP_GET_THREAD_NUM
!$OMP PARALLEL PRIVATE(NTHREADS, TID)
    TID = OMP_GET_THREAD_NUM()
    print*, "Thread",TID,"says hello world!"



!$OMP END PARALLEL
END PROGRAM helloWorld
